-- Limpieza del proyecto de Supabase (rgpzrbwpyaewughahpgo), 2026-09-03.
--
-- El proyecto se comparte con otras cosas de jotajota1302, y habia diez schemas
-- de proyectos parados mas dos aplicaciones enteras dentro de public. Esto deja
-- constancia de lo aplicado; NO hace falta volver a ejecutarlo.
--
-- Se queda: falm, cuentos, comic, public, y los del sistema (auth, storage,
-- realtime, cron, vault, extensions, graphql, supabase_migrations, pgbouncer).

-- ---------------------------------------------------------------------------
-- 1. El agujero: 14 tablas en public con RLS APAGADO y anon con select/insert
-- ---------------------------------------------------------------------------
-- patients, doctors, appointments, messages, message_threads, documents,
-- treatments, doctor_availability, subscriptions, users, audit_log, faqs,
-- content, content_categories.
--
-- Tenian politicas escritas, pero sin "enable row level security" Postgres las
-- ignora. Y public es el schema que PostgREST expone por defecto, con la clave
-- anon publicada en el bundle de ligafalm.com. Cualquiera podia leerlas y
-- escribir en ellas.
--
-- Eran de una aplicacion para un medico, en standby. Copiadas a
-- bk_medico_20260903 y borradas de public (mas la vista faqs_view).

-- ---------------------------------------------------------------------------
-- 2. Las tablas optica_* de public
-- ---------------------------------------------------------------------------
-- Diez tablas de otro proyecto parado. Estas si tenian RLS. Copiadas a
-- bk_optica_20260903 y borradas.
-- public queda con 6 tablas, todas con RLS y politicas.

-- ---------------------------------------------------------------------------
-- 3. Schemas de proyectos antiguos: a medias, y con una leccion cara
-- ---------------------------------------------------------------------------
-- Renombrar un schema que PostgREST tiene en su lista de expuestos TUMBA LA API
-- ENTERA: PGRST002, "Could not query the database for the schema cache", y deja
-- de responder todo el proyecto, FALM incluida. Paso dos veces.
--
-- La lista que manda NO es solo la del dashboard: es un parametro del rol
-- authenticator. Se lee asi:
--
--   select rolname, rolconfig from pg_roles where rolname = 'authenticator';
--
-- El 2026-09-03 valia "public, storage, ai_agents, falm, cuentos, comic", con
-- ai_agents dentro aunque en el dashboard ya se habia quitado. Por eso archivar
-- taxes (fuera de la lista) fue bien y archivar ai_agents volvio a tirar la API.
--
-- Receta antes de renombrar o borrar CUALQUIER schema:
--   1. Mirar rolconfig de authenticator y comprobar que no esta en la lista.
--   2. Si esta, quitarlo (dashboard: Settings -> API -> Exposed schemas) y
--      verificar que rolconfig ya no lo nombra.
--   3. Renombrar de uno en uno, comprobando la API entre medias:
--        curl -s -X POST ".../rest/v1/rpc/nombre_de_equipo" --          -H "apikey: <anon>" -H "Content-Profile: falm" --          -H "Content-Type: application/json" -d '{"p_nombre":"BABUSIANOS"}'
--      Tiene que devolver "BABUSIANOS", no PGRST002.
--   4. Si se cae: renombrar de vuelta. Se recupera en segundos.
--
-- Estado: archivado solo bk_taxes_20260903. Siguen con su nombre original
-- skills_registry, teatro, university, mcp_shield, n8n_workflows, ai_agents y
-- csv_ai, con los permisos que tenian.

-- ---------------------------------------------------------------------------
-- 4. PENDIENTE: dos triggers ajenos colgando de auth.users
-- ---------------------------------------------------------------------------
-- Cada alta de usuario en FALM disparaba estos dos, de otros proyectos, que
-- escribian en sus tablas:
--
--   on_auth_user_created         -> ai_agents.handle_new_user
--   on_auth_user_created_csv_ai  -> csv_ai.handle_new_user
--
-- Hay que quitarlos ANTES de borrar de verdad esos schemas. Ejecutar en el
-- editor SQL de Supabase (tocar el schema auth desde fuera esta capado):
--
--   drop trigger if exists on_auth_user_created on auth.users;
--   drop trigger if exists on_auth_user_created_csv_ai on auth.users;
--
-- Comprobacion despues:
--
--   select tgrelid::regclass, tgname from pg_trigger
--    where not tgisinternal and tgrelid = 'auth.users'::regclass;

-- ---------------------------------------------------------------------------
-- 5. Lo que quedo en public, por decidir
-- ---------------------------------------------------------------------------
-- generated_chapters, runs, user_data, user_profiles, user_provider_keys,
-- wallets. Todas con RLS y politicas, asi que no corren prisa, pero no se ha
-- identificado de que proyecto son. Si son de cuentos o comic, su sitio es su
-- schema; si no son de nada, fuera.
--
-- La funcion public.handle_new_user (inserta en user_profiles y user_data) NO
-- esta enganchada a ningun trigger. Estas otras quedaron huerfanas al borrar
-- las tablas del proyecto medico y se pueden borrar: get_my_patient_id,
-- get_my_role, is_staff, handle_new_auth_user, auto_generate_slug,
-- generate_slug.
